### ISSUE TITLE
Ease of Use

### ISSUE THREAD

**Issue by SEALCOOL13** [tgdrive/rdebrid-ui#1]
Bro, I really want to use this as it looks so fresh and exactly suited to my needs but I'll be honest.

It's too developer-y to set up. I say this as a person who is fond of tinkering around but can't you provide a script type file to run in the Linux Terminal/PowerShell and then open in the browser?

I only say this because I know nothing about Docker and the few times I've tried it have ended badly (probably my own mistakes).

If I made an unreasonable request or overstepped with this Issue, I'm truly sorry. I can't even begin to understand how much work goes into development these days.

Just a suggestion if you could make it easier to set-up.

**Comment by divyam234** [comment]
@SEALCOOL13  you can deploy it on cloudflare pages  you don't need to setup docker its very easy make a cloudflare account and folllow readme.Search cloudflare pages you will find many videos regarding that
