### ISSUE TITLE
Search option is not working

### ISSUE THREAD

**Issue by dbkrsn** [tgdrive/rdebrid-ui#2]
Search option is not working, it is returning 500. Other functionalities are working.

<img width="739" alt="image-1" src="https://github.com/user-attachments/assets/bb01ae6b-fb98-4979-be6b-9a7c67c4338c">

<img width="386" alt="image-2" src="https://github.com/user-attachments/assets/e4410ac7-7275-4fe6-a881-0afb1d18ff06">

**Comment by divyam234** [comment]
@dbkrsn where have you deployed  this?
make sure https://bt4gprx.com isn't  blocked for you.You can use  proxy in `PROXY_URL` env  to bypass that.

**Comment by dbkrsn** [comment]
Deployed in Cloudflare. It’s blocked by my ISP, that explains why the search is not working. Thanks for the information.
